### ISSUE TITLE
delete task does not check for current user = task creator

### ISSUE THREAD

**Issue by nicholaslum444** [nicholaslum444/cs2102project#11]
it's commented as such in the code but it's not implemented.

This is a security problem as people can craft their own post request and delete other people's post.

However is security important for our app? if not important, we don't implement it and we remove the comment. Thoughts @heyjiawei

**Comment by heyjiawei** [comment]
Yep, I am aware of this. Security is not important since users will primarily be navigating via the website links but if they look into our code, we might be marked against this. I'll edit it to ensure task can only be deleted by the creator and admins
